dataset:
  target: dataset.LRHRRef.LRHRRefDataset
  params:
    # Path to the file list.
    dataroot_hr: /content/CRefDiff_Pandala_v2/dataset/ALL_2/ALL_2/test/HR
    dataroot_lr: /content/CRefDiff_Pandala_v2/dataset/ALL_2/ALL_2/test/LR
    dataroot_ref: /content/CRefDiff_Pandala_v2/dataset/ALL_2/ALL_2/test/Ref
    split: "val"
    data_len: 1456
    use_ColorJitter: false
    gt_as_ref: false

data_loader:
  batch_size: 8
  shuffle: false
  num_workers: 8
  drop_last: false

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform